[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Biz One"
authors = [{name = "Marcos Barbisan", email = "barbisan@akrsistemas.com.br"}]
dynamic = ["version", "description"]
